### ISSUE TITLE
PR Make custom themes work on microsites.  9282 Test

### ISSUE THREAD

**Issue by laq** [eduNEXT/edunext-platform#6]
On the branch testing_pr_9282  https://github.com/eduNEXT/edunext-platform/commit/b4900fba1e94a39c7608a31beab4e731a70f7a83 
The pr was applied and conflicts with our code were resolved. It seems ok and it does not break, but I don't know, having in mind our microsite changes, if it has sense. The code runs.

**Comment by felipemontoya** [comment]
This PR was closed upstream and is no longer necessary
