### ISSUE TITLE
edx_sga fileupload is not a function

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/edunext-platform#729]
![image](https://user-images.githubusercontent.com/33465240/213745050-1f1a710c-2342-4038-92af-1eb7476a2aab.png)

When using edx_sga the `GRADE_SUBMISSIONS` button doesn't work. The console shows those errors.

**Comment by mariajgrimaldi** [comment]
After some research, we've found that this error is related to CloudFront configurations. So we've escalated this issue to the Atlas team @eduNEXT/atlas-team.

**Comment by MoisesGSalas** [comment]
This seems to be an issue with configuration rather than code. I will close the issue as it doesn't require code changes here. It will be tracked internally.
