### ISSUE TITLE
courses from a different tenant are displayed in the mobile apps

### ISSUE THREAD

**Issue by juancamilom** [eduNEXT/edunext-platform#734]
in android mobile apps (I have not tested iOS yet) the list of courses is including courses from other tenants.
here is the example from one mobile app:
![image](https://user-images.githubusercontent.com/4583648/219198736-fa084945-8fbd-4534-b854-3b2f6bb8385e.png)

the web application is only showing the right ones.

@felipemontoya fyi

**Comment by felipemontoya** [comment]
@eduNEXT/django-plugins-teco it looks like this is a badly supported filter on the APIs:

/api/mobile/v1/users/johnsmith/course_enrollments/
/api/mobile/v0.5/users/johnsmith/course_enrollments/

**Comment by mariajgrimaldi** [comment]
can you check if the installation where this was tested has the following configs? 

```
"OPEN_EDX_FILTERS_CONFIG": {
    "org.openedx.learning.course_enrollments_site.filter.requested.v1": {
        "fail_silently": false,
        "pipeline": [
            "eox_tenant.filters.pipeline.FilterUserCourseEnrollmentsByTenant"
        ]
    }
},
```

cc @Ian2012 @DeimerM @DonatoBD

**Comment by Ian2012** [comment]
It doesn't. I'm working on it
