### ISSUE TITLE
Backport HomepageRenderStarted and CatalogRenderStarted filters

### ISSUE THREAD

**Issue by MaferMazu** [eduNEXT/edunext-platform#735]
# Description
This PR #665 was merged in mango.master, and limonero.master but it wasn't merged in release, and for that reason, we didn't take it in account in the nuez migration, and It is not in upstream.

Are we going to migrate that PR?

cc @santiagosuarezedunext

**Comment by santiagosuarezedunext** [comment]
Ya la estoy revisando 👍

**Comment by santiagosuarezedunext** [comment]
Este feature es necesario para [el sandbox de openedx](https://sandbox.openedx.org/) por lo que se va a tener que migrar cuando se migre el sandbox. (actualmente esta en Mango)
El responsable de migrar esta funcionalidad es el equipo que mantenga el sandbox.

Sugiero que 
Primero se defina quienes son los responsables de mantener el sandbox 
segundo creo que en el momento de hacer la migración se puede decidir si  esto se manda o no a upstream 
(Voy a investigar esos dos puntos)

Nota:
Este feature busca facilitar la forma en la que se extiende la plataforma, así que los clientes finales son los backend developers, por tanto son ustedes los que deben decidir si hacen upstream de esto, si lo usan y les sirve si sería buena idea hacer el upstream.

**Comment by santiagosuarezedunext** [comment]
Hablando con Felipe me comenta que efectivamente eduNEXT es el encargado de mantener ese sandbox de openedx. 
Deberiamos migrarlo a cada versión que salga, y lo hariamos de una forma similar a como migramos el SaaS, entre Dedalo Atlas y Service Delivery.

En ese orden de ideas este issue queda pendiente y lo revisaremos cuando hagamos la migración

**Comment by MaferMazu** [comment]
I will close this because it has lost its purpose. Please feel free to reopen it if necessary.
